In [1]:
import numpy as np

1. Whenever doing numerical computation we can use this library.


In [2]:
marks = [10,20,30]

In [140]:
# i want to mutiply 2 in every element in the array. i cant do this list(we can, but we need iterate those elements using loop.little complex comparatively using numpy)
#if we can create a numpy array we can
marks*2

[10, 20, 30, 10, 20, 30]

In [4]:
marks+[2]

[10, 20, 30, 2]

In [5]:
type(marks)

list

In [6]:
#create numpy array

arr = np.array(marks)
arr

array([10, 20, 30])

In [7]:
type(arr)

numpy.ndarray

In [8]:
arr*2

array([20, 40, 60])

In [9]:
arr+2

array([12, 22, 32])

In [10]:
# creating array using arange

a = np.arange(1,10)
b = np.arange(1,10,2)
print(a)
print(b)

[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [11]:
np.arange(10,100,10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [12]:
type(a)

numpy.ndarray

In [13]:
# linspace is return evenly separated values
# in this below example i want the 10 numbers in 1 to 10 and next example i want 100 numbers in 1 to 5. 
# this is called evenly separated values 
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [14]:
np.linspace(1,5,100)

array([1.        , 1.04040404, 1.08080808, 1.12121212, 1.16161616,
       1.2020202 , 1.24242424, 1.28282828, 1.32323232, 1.36363636,
       1.4040404 , 1.44444444, 1.48484848, 1.52525253, 1.56565657,
       1.60606061, 1.64646465, 1.68686869, 1.72727273, 1.76767677,
       1.80808081, 1.84848485, 1.88888889, 1.92929293, 1.96969697,
       2.01010101, 2.05050505, 2.09090909, 2.13131313, 2.17171717,
       2.21212121, 2.25252525, 2.29292929, 2.33333333, 2.37373737,
       2.41414141, 2.45454545, 2.49494949, 2.53535354, 2.57575758,
       2.61616162, 2.65656566, 2.6969697 , 2.73737374, 2.77777778,
       2.81818182, 2.85858586, 2.8989899 , 2.93939394, 2.97979798,
       3.02020202, 3.06060606, 3.1010101 , 3.14141414, 3.18181818,
       3.22222222, 3.26262626, 3.3030303 , 3.34343434, 3.38383838,
       3.42424242, 3.46464646, 3.50505051, 3.54545455, 3.58585859,
       3.62626263, 3.66666667, 3.70707071, 3.74747475, 3.78787879,
       3.82828283, 3.86868687, 3.90909091, 3.94949495, 3.98989

In [15]:
lst = list(range(0,10))
lst

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [16]:
# in list format 
[i**2 for i in lst]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [17]:
# checking execution time

%timeit [i**2 for i in lst]

541 ns ± 94.4 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [18]:
#  numpy format

arr = np.array(lst)

arr**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [19]:
%timeit arr**2

607 ns ± 192 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


### slicing

In [20]:
arr = np.arange(10,30,3)
arr

array([10, 13, 16, 19, 22, 25, 28])

In [21]:
# i want only 13 to 25

arr[1:-2]

array([13, 16, 19, 22])

In [22]:
arr [0]

10

In [23]:
arr[4]

22

In [24]:
arr[1] = 110
arr

array([ 10, 110,  16,  19,  22,  25,  28])

In [25]:
# ndim return the dimention of the array
arr.ndim

1

In [26]:
# shape retur the shape of the array(row , column)
arr.shape

(7,)

In [27]:
# size return the total elements of the array
arr.size

7

### Creating 2D array

In [28]:
lst_2d = [[1,2,3,4],[5,6,7,8]]
lst_2d

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [29]:
arr_2d = np.array(lst_2d)
arr_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [30]:
print(arr_2d.ndim)

print('*'*10)

print(arr_2d.shape)

print('*'*10)

print(arr_2d.size)

2
**********
(2, 4)
**********
8


In [31]:
arr_2d*2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [32]:
arr_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [33]:
arr_2d[1][2]

7

In [34]:
arr_2d[0]

array([1, 2, 3, 4])

In [35]:
arr_2d[0][2]

3

In [36]:
arr_2d[0:1]

array([[1, 2, 3, 4]])

In [37]:
arr_2d[0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [38]:
np.array([1,2]).shape

(2,)

In [39]:
np.array([[1,2]]).shape

(1, 2)

In [40]:
temp = np.array([1,2])
temp

array([1, 2])

In [41]:
temp.ndim

1

In [42]:
temp = np.array([[1,2]])
temp

array([[1, 2]])

In [43]:
a = np.array([[1,2,3,4,5]])
a.ndim

2

In [44]:
a

array([[1, 2, 3, 4, 5]])

## Reshape

In [45]:
a =np.linspace(1,10,18)

In [46]:
a.shape

(18,)

In [47]:
a.ndim

1

In [48]:
b = a.reshape((6,3))
b

array([[ 1.        ,  1.52941176,  2.05882353],
       [ 2.58823529,  3.11764706,  3.64705882],
       [ 4.17647059,  4.70588235,  5.23529412],
       [ 5.76470588,  6.29411765,  6.82352941],
       [ 7.35294118,  7.88235294,  8.41176471],
       [ 8.94117647,  9.47058824, 10.        ]])

In [49]:
c = a.reshape((3,6))
c

array([[ 1.        ,  1.52941176,  2.05882353,  2.58823529,  3.11764706,
         3.64705882],
       [ 4.17647059,  4.70588235,  5.23529412,  5.76470588,  6.29411765,
         6.82352941],
       [ 7.35294118,  7.88235294,  8.41176471,  8.94117647,  9.47058824,
        10.        ]])

In [50]:
b.shape

(6, 3)

In [51]:
b.ndim

2

In [52]:
a = c.reshape((9,2))
a

array([[ 1.        ,  1.52941176],
       [ 2.05882353,  2.58823529],
       [ 3.11764706,  3.64705882],
       [ 4.17647059,  4.70588235],
       [ 5.23529412,  5.76470588],
       [ 6.29411765,  6.82352941],
       [ 7.35294118,  7.88235294],
       [ 8.41176471,  8.94117647],
       [ 9.47058824, 10.        ]])

In [53]:
b = np.arange(20).reshape(5,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [54]:
b[0:4,0:2]

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [55]:
b[1:3,0:5]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [56]:
b[:,:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

## Special matrix

In [57]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [58]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [59]:
np.zeros((4))

array([0., 0., 0., 0.])

In [60]:
np.ones(4)

array([1., 1., 1., 1.])

In [61]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [62]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [63]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Slicing

In [64]:
arr = np.linspace(1,20,20).reshape(4,5)

In [65]:
arr

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.]])

In [66]:
# 2d matrix slicing
#arr[row , column]

arr[0:3,0:4]

array([[ 1.,  2.,  3.,  4.],
       [ 6.,  7.,  8.,  9.],
       [11., 12., 13., 14.]])

In [67]:
arr[1:3,2:4]

array([[ 8.,  9.],
       [13., 14.]])

In [68]:
arr[3:, 4:]

array([[20.]])

## Functions

In [69]:
arr.mean()

10.5

In [70]:
np.mean(arr)

10.5

In [71]:
np.sum(arr)

210.0

In [72]:
np.median(arr)

10.5

### Operator 

In [73]:
arr +2

array([[ 3.,  4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11., 12.],
       [13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22.]])

In [74]:
arr - 2

array([[-1.,  0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12., 13.],
       [14., 15., 16., 17., 18.]])

In [75]:
arr + arr

array([[ 2.,  4.,  6.,  8., 10.],
       [12., 14., 16., 18., 20.],
       [22., 24., 26., 28., 30.],
       [32., 34., 36., 38., 40.]])

In [76]:
arr * arr

array([[  1.,   4.,   9.,  16.,  25.],
       [ 36.,  49.,  64.,  81., 100.],
       [121., 144., 169., 196., 225.],
       [256., 289., 324., 361., 400.]])

### Masking

In [77]:
a = np.arange(12).reshape(3,4)

In [78]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [79]:
mask = a<7
mask

array([[ True,  True,  True,  True],
       [ True,  True,  True, False],
       [False, False, False, False]])

In [80]:
np.sum(mask)

7

In [81]:
a[mask]

array([0, 1, 2, 3, 4, 5, 6])

In [82]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### Matrix multiplication

1. np.matmul(a,b)
2. a@b
3. np.dot(a,b)

In [83]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [84]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [86]:
# this is return multiplication, but it's not an matrix multiplication
a*b

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [89]:
#In matrix multiplication we need first matrix column and second matrix row is to be equal.
b = b.reshape(4,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [90]:
np.matmul(a,b)

array([[ 42,  48,  54],
       [114, 136, 158],
       [186, 224, 262]])

In [91]:
a@b

array([[ 42,  48,  54],
       [114, 136, 158],
       [186, 224, 262]])

In [92]:
np.dot(a,b)

array([[ 42,  48,  54],
       [114, 136, 158],
       [186, 224, 262]])

### Transpose

In [94]:
b.transpose()

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [95]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [98]:
np.transpose(a)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [99]:
a.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

### convert 2d to 1d array

In [100]:
a.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [102]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [103]:
np.ravel(a)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### Merging of array
1. np.hstack()
2. np.vstack()


In [105]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [106]:
a1

array([[1, 1],
       [2, 2]])

In [107]:
a2

array([[3, 3],
       [4, 4]])

In [109]:
np.hstack((a1,a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [111]:
np.vstack((a1,a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

### Split
1. hsplit()
2. vsplit()

In [121]:
x = np.arange(1, 25).reshape(4, 6)
x

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [122]:
np.hsplit(x,2)

[array([[ 1,  2,  3],
        [ 7,  8,  9],
        [13, 14, 15],
        [19, 20, 21]]),
 array([[ 4,  5,  6],
        [10, 11, 12],
        [16, 17, 18],
        [22, 23, 24]])]

In [128]:
np.hsplit(x,3)

[array([[ 1,  2],
        [ 7,  8],
        [13, 14],
        [19, 20]]),
 array([[ 3,  4],
        [ 9, 10],
        [15, 16],
        [21, 22]]),
 array([[ 5,  6],
        [11, 12],
        [17, 18],
        [23, 24]])]

In [139]:
np.vsplit(x,2)

[array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]]),
 array([[13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]])]